### PR TITLE
Import some of the changes from parent repo

### PR DESCRIPTION
**Pull request by xeropresence**

### CODE REVIEW

**Comment by xeropresence** [comment]
There's also some json changes if you wanna pull in those as well

**Comment by DarkDestry** [comment]
I did a manual build of the code. Can you commit the json changes as well? I think the duty tables are there.

**Comment by DarkDestry** [comment]
Otherwise its working

**Comment by DarkDestry** [comment]
Oops I see you commited it already

It doesnt seem to be able to identify the rouletette when in the matching state.

**Pull request merged**
